# Use an official Node.js runtime as the builder image
FROM node:16-alpine

WORKDIR /app

# Copy the package.json file to the container
COPY package.json ./

# Copy the yarn.lock file to the container
COPY yarn.lock ./

# Yalc for local package development
# COPY ./.yalc ./.yalc

# Install the app dependencies
RUN yarn install

# Copy the tsconfig.json to be able to compile the typescript
COPY tsconfig.json ./

EXPOSE 5002

CMD ["yarn", "start:local"]
